### ISSUE TITLE
Formatting problem with Firefox ESR 52

### ISSUE THREAD

**Issue by jgillula** [EFForg/starttls-frontend#191]
We got the following bug report:

> The “www.starttls-everywhere.org” site has a formatting problem when displayed on the current Firefox Extended Support Release (ESR 52), specifically Firefox version 52.0.2 on Windows 7.  See <https://www.mozilla.org/en-US/firefox/organizations/>. The problem is that the kangaroo heading overlaps (and hides) the main text.  See below for a screenshot.

![image001](https://user-images.githubusercontent.com/6627267/42235218-f6c746dc-7eab-11e8-9e02-102db80efa1d.png)

**Comment by sydneyli** [comment]
We got another report of this for Debian, so I'm assuming it's not just a Windows issue.
From the bug report:

> I attach a screenshot of how https://starttls-everywhere.org/policy-list/
> appears on Firefox ESR 52.9.0 (64-bit), the stock Debian browser.  It scaled
> the SVG image to 750x375 px; perhaps, setting main-content's padding-top to
> that value results in a readable page.  Hm... A better method could be to set,
> say, "height: 375; margin-bottom: -170;" in the image style.

![starttls-everywhere](https://user-images.githubusercontent.com/1813285/43148346-ef120bb0-8f19-11e8-9b17-a1408b31eb85.png)

**Comment by sydneyli** [comment]
Looks like you're right; for some reason the SVG's height is being pre-calculated to some fixed value. we'd prefer not to hard-code the image size, though.

using an `embed` tag instead of `img` seems to work, but i'm not sure whether there are caveats to using `embed` (in particular, w.r.t. accessibility) or whether there's a nicer solution. @vbrown608
